name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "statistics-covid-app"
          heroku_email: "lucas.nahuel.espindola1998@gmail.com"
          justlogin: true
      - run: |
          git push heroku master
